// <auto-generated />
namespace BabySitter.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class AddingEmpChildECont : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddingEmpChildECont));
        
        string IMigrationMetadata.Id
        {
            get { return "201710191358175_AddingEmpChildECont"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
